version: "3.9" 
services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./src/postgres/:/var/lib/postgresql/data
    networks:
      - myapp
  # nginx:
  #   container_name: nginx
  #   restart: always
  #   image: "nginx:latest"
  #   ports:
  #     - "85:85"
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #   networks:
  #     - myapp
  #   depends_on: 
  #     - api

  adminer:
    image: adminer
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 8080:8080
    networks:
      - myapp

  api:
      build: .
      env_file: .env
      ports:
        - 5001:5005
      volumes:
        - ./src:/usr/src/app
      networks:
      - myapp

volumes:
  postgres: 
    driver: local

networks:
  myapp:
    driver: bridge